/**
 * Comprehensive University at Buffalo Majors Database
 *
 * This file contains all undergraduate, master's, and PhD programs
 * organized by degree level for use across the HIVE application.
 */

import { type MajorType } from '../types/major';

export const UNDERGRADUATE_MAJORS: MajorType[] = [
  { name: 'Accounting', level: 'undergraduate' },
  { name: 'Acting', level: 'undergraduate' },
  { name: 'Aerospace Engineering', level: 'undergraduate' },
  { name: 'African American Studies', level: 'undergraduate' },
  { name: 'American Studies', level: 'undergraduate' },
  { name: 'Anthropology', level: 'undergraduate' },
  { name: 'Architecture', level: 'undergraduate' },
  { name: 'Art', level: 'undergraduate' },
  { name: 'Art History', level: 'undergraduate' },
  { name: 'Asian Studies', level: 'undergraduate' },
  { name: 'Biochemistry', level: 'undergraduate' },
  { name: 'Bioinformatics & Computational Biology', level: 'undergraduate' },
  { name: 'Biological Sciences', level: 'undergraduate' },
  { name: 'Biomedical Engineering', level: 'undergraduate' },
  { name: 'Biomedical Sciences', level: 'undergraduate' },
  { name: 'Biotechnology', level: 'undergraduate' },
  { name: 'Business Administration', level: 'undergraduate' },
  { name: 'Chemical Engineering', level: 'undergraduate' },
  { name: 'Chemistry', level: 'undergraduate' },
  { name: 'Civil Engineering', level: 'undergraduate' },
  { name: 'Classics', level: 'undergraduate' },
  { name: 'Cognitive Science', level: 'undergraduate' },
  { name: 'Communication', level: 'undergraduate' },
  { name: 'Computational Linguistics', level: 'undergraduate' },
  { name: 'Computational Physics', level: 'undergraduate' },
  { name: 'Computer Engineering', level: 'undergraduate' },
  { name: 'Computer Science', level: 'undergraduate' },
  { name: 'Criminology', level: 'undergraduate' },
  { name: 'Dance', level: 'undergraduate' },
  { name: 'Economics', level: 'undergraduate' },
  { name: 'Electrical Engineering', level: 'undergraduate' },
  { name: 'Engineering Physics', level: 'undergraduate' },
  { name: 'Engineering Science', level: 'undergraduate' },
  { name: 'English', level: 'undergraduate' },
  { name: 'Environmental Design', level: 'undergraduate' },
  { name: 'Environmental Engineering', level: 'undergraduate' },
  { name: 'Environmental Science', level: 'undergraduate' },
  { name: 'Environmental Studies', level: 'undergraduate' },
  { name: 'Environmental Sustainability', level: 'undergraduate' },
  { name: 'Exercise Science', level: 'undergraduate' },
  { name: 'Film Studies', level: 'undergraduate' },
  { name: 'French', level: 'undergraduate' },
  { name: 'Geographic Information Science', level: 'undergraduate' },
  { name: 'Geography', level: 'undergraduate' },
  { name: 'Geological Sciences', level: 'undergraduate' },
  { name: 'German', level: 'undergraduate' },
  { name: 'Global Affairs', level: 'undergraduate' },
  { name: 'Global Gender Studies', level: 'undergraduate' },
  { name: 'Health and Human Services', level: 'undergraduate' },
  { name: 'History', level: 'undergraduate' },
  { name: 'Indigenous Studies', level: 'undergraduate' },
  { name: 'Industrial Engineering', level: 'undergraduate' },
  { name: 'Information Technology & Management', level: 'undergraduate' },
  { name: 'International Studies', level: 'undergraduate' },
  { name: 'International Trade', level: 'undergraduate' },
  { name: 'Italian', level: 'undergraduate' },
  { name: 'Jewish Studies', level: 'undergraduate' },
  { name: 'Law', level: 'undergraduate' },
  { name: 'Legal Studies', level: 'undergraduate' },
  { name: 'Linguistics', level: 'undergraduate' },
  { name: 'Materials Science & Engineering', level: 'undergraduate' },
  { name: 'Mathematics', level: 'undergraduate' },
  { name: 'Mechanical Engineering', level: 'undergraduate' },
  { name: 'Media Study', level: 'undergraduate' },
  { name: 'Medical Laboratory Science', level: 'undergraduate' },
  { name: 'Music', level: 'undergraduate' },
  { name: 'Music Theatre', level: 'undergraduate' },
  { name: 'Neuroscience', level: 'undergraduate' },
  { name: 'Nuclear Medicine Technology', level: 'undergraduate' },
  { name: 'Nursing', level: 'undergraduate' },
  { name: 'Nursing RN-to-BS', level: 'undergraduate' },
  { name: 'Nutrition Science', level: 'undergraduate' },
  { name: 'Occupational Therapy', level: 'undergraduate' },
  { name: 'Pharmaceutical Sciences', level: 'undergraduate' },
  { name: 'Pharmacology & Toxicology', level: 'undergraduate' },
  { name: 'Pharmacy', level: 'undergraduate' },
  { name: 'Philosophy', level: 'undergraduate' },
  { name: 'Philosophy, Politics & Economics', level: 'undergraduate' },
  { name: 'Physics', level: 'undergraduate' },
  { name: 'Political Science', level: 'undergraduate' },
  { name: 'Psychology', level: 'undergraduate' },
  { name: 'Public Health', level: 'undergraduate' },
  { name: 'Sociology', level: 'undergraduate' },
  { name: 'Spanish', level: 'undergraduate' },
  { name: 'Special Studies', level: 'undergraduate' },
  { name: 'Speech & Hearing Science', level: 'undergraduate' },
  { name: 'Statistics', level: 'undergraduate' },
  { name: 'Theatre', level: 'undergraduate' },
  { name: 'Theatre Design/Technology', level: 'undergraduate' },
  { name: 'Urban & Public Policy Studies', level: 'undergraduate' }
];
