import type { Meta, StoryObj } from '@storybook/react';
import React from 'react';
import { 
  Heart, MessageCircle, Share2, Bookmark, MoreHorizontal, 
  Clock, Users, Calendar, Star, Zap, Trophy, Target,
  MapPin, BookOpen, Coffee, Music, Gamepad2, Dumbbell,
  Camera, Video, FileText, Link, Hash, AtSign,
  ChevronRight, Plus, Filter, TrendingUp, Eye,
  CheckCircle, AlertCircle, Timer, Play, Pause
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/card';
import { Button } from '../../../components/ui/button';
import { Avatar, AvatarFallback, AvatarImage } from '../../../components/ui/avatar';
import { Badge } from '../../../components/ui/badge';
import { Progress } from '../../../components/ui/progress';

const meta: Meta = {
  title: '03-Molecules/Social-Feed-Components/Feed & Rituals System',
  parameters: {
    docs: {
      description: {
        component: `
# HIVE Feed & Rituals System

The social utility feed system for University at Buffalo students, combining meaningful campus content with productive ritual coordination. This molecular system creates authentic community engagement around shared activities and campus life coordination.

## Social Utility Philosophy
- **Content with Purpose** - Every post serves community coordination or campus connection
- **Ritual-Driven Engagement** - Regular, meaningful activities that build campus community
- **Tool-Powered Content** - Posts generated by student tools, not performative social media
- **Campus Context Always** - All content relates to UB student life and community building

## Feed Categories
- **Community Coordination** - Space activities, study sessions, campus events
- **Ritual Participation** - Daily/weekly activities students do together
- **Campus Social Proof** - Real activity happening across university
- **Tool-Generated Content** - Results from student-created coordination tools

## Ritual Types
- **Study Rituals** - Group study sessions, library meetups, academic coordination
- **Social Rituals** - Floor activities, dining hall meetups, campus exploration
- **Wellness Rituals** - Gym sessions, walks, mindfulness activities
- **Creative Rituals** - Art sessions, music practice, project collaboration

## Engagement Patterns
- **Meaningful Reactions** - "I'm in", "Need this", "Can help" instead of empty likes
- **Coordination Comments** - Practical responses about timing, location, logistics
- **Social Proof Display** - Show real participation, not just engagement metrics
- **Community Building** - Strengthen actual relationships through shared activities

## Content Flow
- **Tool-Generated Posts** - Study session coordinators, event planners create content
- **Ritual Announcements** - Students invite others to join regular activities
- **Campus Updates** - Real-time coordination happening across spaces
- **Social Recognition** - Celebrate community participation and tool success
        `
      }
    }
  }
};

export default meta;
type Story = StoryObj;

// Campus Feed Data
const campusFeedData = [
  {
    id: 'study-session-cse474',
    type: 'tool-generated',
    creator: {
      name: 'Sarah Chen',
      handle: '@sarahc.cs',
      avatar: '/api/placeholder/40/40',
      spaces: ['CSE 474 Study Group', 'Engineering Students']
    },
    tool: {
      name: 'Study Session Planner',
      type: 'coordination'
    },
    content: {
      title: 'ML Study Session Tomorrow',
      description: 'Covering neural networks and backpropagation. Study room 312 in Lockwood Library.',
      time: '2 hours ago',
      details: {
        when: 'Tomorrow, 2:00 PM - 4:00 PM',
        where: 'Lockwood Library, Room 312',
        spots: '6 spots available',
        materials: 'Bring Chapter 4 notes and practice problems'
      }
    },
    engagement: {
      participants: 8,
      interested: 12,
      comments: 5,
      social_proof: ['@mike.cs', '@jenny.eng', '@alex.math', '+5 others joined']
    },
    actions: ['Join Session', 'Mark Interested', 'Get Materials']
  },
  {
    id: 'floor-potluck-ellicott',
    type: 'ritual',
    creator: {
      name: 'Alex Rivera',
      handle: '@alex.floor3',
      avatar: '/api/placeholder/40/40',
      spaces: ['Ellicott Floor 3', 'Campus Dining']
    },
    ritual: {
      name: 'Weekly Floor Potluck',
      frequency: 'Every Friday',
      streak: 6,
      participants: 18
    },
    content: {
      title: 'Floor 3 Potluck Night',
      description: 'Bringing the floor together with homemade food and good vibes. Theme this week: comfort food!',
      time: '4 hours ago',
      details: {
        when: 'Friday, 6:00 PM',
        where: 'Floor 3 Common Room',
        theme: 'Comfort Food',
        signup: '12/18 spots filled'
      }
    },
    engagement: {
      participants: 12,
      interested: 6,
      comments: 8,
      social_proof: ['@maria.floor3', '@david.floor3', '@sam.floor3', '+9 others signed up']
    },
    actions: ['Sign Up', 'See Menu', 'Suggest Dish']
  },
  {
    id: 'gym-ritual-wellness',
    type: 'ritual',
    creator: {
      name: 'Jordan Williams',
      handle: '@jordan.wellness',
      avatar: '/api/placeholder/40/40',
      spaces: ['Campus Wellness', 'Alumni Arena Regulars']
    },
    ritual: {
      name: 'Morning Gym Session',
      frequency: 'Daily',
      streak: 12,
      participants: 25
    },
    content: {
      title: '7 AM Gym Squad',
      description: 'Start the day strong with the morning crew. All fitness levels welcome - we support each other!',
      time: '6 hours ago',
      details: {
        when: 'Daily, 7:00 AM - 8:30 AM',
        where: 'Alumni Arena Fitness Center',
        focus: 'Full body strength training',
        experience: 'All levels welcome'
      }
    },
    engagement: {
      participants: 8,
      interested: 15,
      comments: 12,
      social_proof: ['@mike.fitness', '@sarah.wellness', '@taylor.health', '+5 others checked in today']
    },
    actions: ['Join Tomorrow', 'Get Workout', 'Find Buddy']
  },
  {
    id: 'library-study-ritual',
    type: 'coordination',
    creator: {
      name: 'Emma Thompson',
      handle: '@emma.psych',
      avatar: '/api/placeholder/40/40',
      spaces: ['Psychology Research', 'Quiet Study Spaces']
    },
    content: {
      title: 'Silent Study Session',
      description: 'Deep focus time for everyone working on research papers and projects. No talking, just productive energy.',
      time: '1 hour ago',
      details: {
        when: 'Right now - 6:00 PM',
        where: 'Lockwood Library, 4th Floor',
        type: 'Silent study',
        duration: '3 hours remaining'
      }
    },
    engagement: {
      participants: 15,
      interested: 8,
      comments: 3,
      social_proof: ['@david.research', '@anna.thesis', '@james.study', '+12 others studying now']
    },
    actions: ['Join Now', 'Find Spot', 'Set Timer']
  }
];

// Ritual Categories Data
const ritualCategories = [
  {
    id: 'study',
    name: 'Study Together',
    icon: BookOpen,
    color: 'blue',
    count: 12,
    active: 'Now',
    examples: ['Library sessions', 'Group review', 'Project work']
  },
  {
    id: 'social',
    name: 'Social Activities',
    icon: Coffee,
    color: 'green',
    count: 8,
    active: '3 today',
    examples: ['Floor dinners', 'Movie nights', 'Game sessions']
  },
  {
    id: 'wellness',
    name: 'Stay Healthy',
    icon: Dumbbell,
    color: 'purple',
    count: 6,
    active: 'Morning',
    examples: ['Gym sessions', 'Walks', 'Yoga classes']
  },
  {
    id: 'creative',
    name: 'Create Together',
    icon: Music,
    color: 'orange',
    count: 4,
    active: 'Evening',
    examples: ['Art sessions', 'Music practice', 'Writing groups']
  }
];

// Feed Content Story
export const CampusFeedInterface: Story = {
  render: () => {
    const [filter, setFilter] = React.useState('all');
    const [engagementMode, setEngagementMode] = React.useState<string>('view');

    const filterOptions = [
      { id: 'all', label: 'All Activity', count: campusFeedData.length },
      { id: 'tools', label: 'Tool Updates', count: 1 },
      { id: 'rituals', label: 'Rituals', count: 2 },
      { id: 'coordination', label: 'Coordination', count: 1 }
    ];

    const filteredFeed = campusFeedData.filter(post => {
      if (filter === 'all') return true;
      if (filter === 'tools') return post.type === 'tool-generated';
      if (filter === 'rituals') return post.type === 'ritual';
      if (filter === 'coordination') return post.type === 'coordination';
      return true;
    });

    return (
      <div className="w-full max-w-6xl mx-auto p-8 bg-gradient-to-br from-blue-50 to-indigo-50">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Campus Feed & Rituals</h2>
          <p className="text-lg text-gray-600">Social utility for University at Buffalo students</p>
        </div>

        <div className="grid lg:grid-cols-4 gap-6">
          {/* Left Sidebar - Filters & Rituals */}
          <div className="lg:col-span-1 space-y-6">
            {/* Activity Filters */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-lg">Activity Feed</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                {filterOptions.map((option) => (
                  <button
                    key={option.id}
                    onClick={() => setFilter(option.id)}
                    className={`w-full flex items-center justify-between p-3 rounded-lg text-left transition-colors ${
                      filter === option.id
                        ? 'bg-blue-600 text-white'
                        : 'hover:bg-gray-100'
                    }`}
                  >
                    <span className="font-medium">{option.label}</span>
                    <Badge variant={filter === option.id ? 'secondary' : 'outline'} className="text-xs">
                      {option.count}
                    </Badge>
                  </button>
                ))}
              </CardContent>
            </Card>

            {/* Ritual Categories */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-lg">Active Rituals</CardTitle>
                <CardDescription>Regular campus activities</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {ritualCategories.map((category) => {
                  const IconComponent = category.icon;
                  return (
                    <div key={category.id} className="flex items-center gap-3 p-3 rounded-lg hover:bg-gray-50 cursor-pointer">
                      <div className={`p-2 rounded-lg ${
                        category.color === 'blue' ? 'bg-blue-100 text-blue-600' :
                        category.color === 'green' ? 'bg-green-100 text-green-600' :
                        category.color === 'purple' ? 'bg-purple-100 text-purple-600' :
                        'bg-orange-100 text-orange-600'
                      }`}>
                        <IconComponent className="h-4 w-4" />
                      </div>
                      <div className="flex-1">
                        <p className="font-medium text-gray-900">{category.name}</p>
                        <p className="text-sm text-gray-600">{category.active}</p>
                      </div>
                      <Badge variant="outline" className="text-xs">
                        {category.count}
                      </Badge>
                    </div>
                  );
                })}
              </CardContent>
            </Card>
          </div>

          {/* Main Feed */}
          <div className="lg:col-span-3 space-y-6">
            {/* Create Post Interface */}
            <Card>
              <CardContent className="p-4">
                <div className="flex items-center gap-4">
                  <Avatar className="h-10 w-10">
                    <AvatarImage src="/api/placeholder/40/40" />
                    <AvatarFallback className="bg-blue-100 text-blue-600">YU</AvatarFallback>
                  </Avatar>
                  <div className="flex-1">
                    <button className="w-full text-left p-3 bg-gray-50 rounded-lg text-gray-500 hover:bg-gray-100">
                      Start a ritual, coordinate an activity, or share campus updates...
                    </button>
                  </div>
                </div>
                <div className="flex items-center gap-3 mt-4 ml-14">
                  <Button size="sm" variant="outline" className="gap-2">
                    <Calendar className="h-4 w-4" />
                    Schedule Activity
                  </Button>
                  <Button size="sm" variant="outline" className="gap-2">
                    <Users className="h-4 w-4" />
                    Start Ritual
                  </Button>
                  <Button size="sm" variant="outline" className="gap-2">
                    <Zap className="h-4 w-4" />
                    Use Tool
                  </Button>
                </div>
              </CardContent>
            </Card>

            {/* Feed Posts */}
            <div className="space-y-6">
              {filteredFeed.map((post) => (
                <Card key={post.id} className="overflow-hidden">
                  <CardHeader className="pb-3">
                    <div className="flex items-start justify-between">
                      <div className="flex items-center gap-3">
                        <Avatar className="h-10 w-10">
                          <AvatarImage src={post.creator.avatar} />
                          <AvatarFallback className="bg-blue-100 text-blue-600">
                            {post.creator.name.charAt(0)}
                          </AvatarFallback>
                        </Avatar>
                        <div>
                          <div className="flex items-center gap-2">
                            <p className="font-semibold text-gray-900">{post.creator.name}</p>
                            <p className="text-gray-600">{post.creator.handle}</p>
                            {post.type === 'tool-generated' && (
                              <Badge variant="outline" className="text-xs">
                                <Zap className="h-3 w-3 mr-1" />
                                Tool
                              </Badge>
                            )}
                            {post.type === 'ritual' && (
                              <Badge variant="outline" className="text-xs">
                                <Target className="h-3 w-3 mr-1" />
                                Ritual
                              </Badge>
                            )}
                          </div>
                          <div className="flex items-center gap-2 text-sm text-gray-500">
                            <span>{post.content.time}</span>
                            <span>•</span>
                            <span>{post.creator.spaces[0]}</span>
                          </div>
                        </div>
                      </div>
                      <Button size="sm" variant="ghost">
                        <MoreHorizontal className="h-4 w-4" />
                      </Button>
                    </div>
                  </CardHeader>

                  <CardContent>
                    <div className="space-y-4">
                      {/* Post Content */}
                      <div>
                        <h3 className="text-lg font-semibold text-gray-900 mb-2">
                          {post.content.title}
                        </h3>
                        <p className="text-gray-700">{post.content.description}</p>
                      </div>

                      {/* Post Details */}
                      <div className="bg-gray-50 rounded-lg p-4">
                        <div className="grid grid-cols-2 gap-4 text-sm">
                          {Object.entries(post.content.details).map(([key, value]) => (
                            <div key={key}>
                              <p className="font-medium text-gray-700 capitalize">
                                {key.replace('_', ' ')}
                              </p>
                              <p className="text-gray-600">{value}</p>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Ritual Progress (if applicable) */}
                      {post.ritual && (
                        <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <Trophy className="h-4 w-4 text-green-600" />
                              <span className="font-medium text-green-800">{post.ritual.name}</span>
                            </div>
                            <Badge className="bg-green-100 text-green-700">
                              {post.ritual.streak} week streak
                            </Badge>
                          </div>
                          <div className="flex items-center gap-2 text-sm text-green-700">
                            <Calendar className="h-3 w-3" />
                            <span>{post.ritual.frequency}</span>
                            <span>•</span>
                            <Users className="h-3 w-3" />
                            <span>{post.ritual.participants} regular participants</span>
                          </div>
                        </div>
                      )}

                      {/* Social Proof */}
                      <div className="bg-blue-50 rounded-lg p-3">
                        <div className="flex items-center gap-2 text-sm text-blue-800">
                          <Eye className="h-3 w-3" />
                          <span>{post.engagement.social_proof.join(', ')}</span>
                        </div>
                      </div>

                      {/* Engagement Actions */}
                      <div className="flex items-center justify-between pt-2 border-t border-gray-200">
                        <div className="flex items-center gap-6">
                          <button className="flex items-center gap-2 text-gray-600 hover:text-blue-600">
                            <Heart className="h-4 w-4" />
                            <span className="text-sm">{post.engagement.participants} joined</span>
                          </button>
                          <button className="flex items-center gap-2 text-gray-600 hover:text-green-600">
                            <MessageCircle className="h-4 w-4" />
                            <span className="text-sm">{post.engagement.comments} comments</span>
                          </button>
                          <button className="flex items-center gap-2 text-gray-600 hover:text-purple-600">
                            <Star className="h-4 w-4" />
                            <span className="text-sm">{post.engagement.interested} interested</span>
                          </button>
                        </div>

                        <div className="flex items-center gap-2">
                          {post.actions.map((action, index) => (
                            <Button 
                              key={index} 
                              size="sm" 
                              variant={index === 0 ? 'default' : 'outline'}
                              className="text-xs"
                            >
                              {action}
                            </Button>
                          ))}
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-8 bg-indigo-50 rounded-xl p-6 border border-indigo-100">
          <h4 className="font-semibold text-indigo-900 mb-2">Social Utility Feed Principles</h4>
          <ul className="text-sm text-indigo-800 space-y-1">
            <li>• Every post serves community coordination or campus connection</li>
            <li>• Ritual-driven engagement builds lasting campus community</li>
            <li>• Tool-generated content eliminates performative social media</li>
            <li>• Meaningful reactions focus on participation, not empty engagement</li>
          </ul>
        </div>
      </div>
    );
  }
};

// Ritual Creation Interface Story
export const RitualCreationInterface: Story = {
  render: () => {
    const [selectedCategory, setSelectedCategory] = React.useState('study');
    const [ritualType, setRitualType] = React.useState('');
    const [frequency, setFrequency] = React.useState('');

    const ritualTemplates = {
      study: [
        { id: 'library-session', name: 'Library Study Session', description: 'Quiet focused work time', duration: '2-3 hours' },
        { id: 'group-review', name: 'Course Review Group', description: 'Collaborative exam prep', duration: '1-2 hours' },
        { id: 'project-work', name: 'Project Work Session', description: 'Team project coordination', duration: '2-4 hours' }
      ],
      social: [
        { id: 'floor-dinner', name: 'Floor Community Dinner', description: 'Shared meals and conversation', duration: '1-2 hours' },
        { id: 'movie-night', name: 'Movie Night', description: 'Films and discussion', duration: '2-3 hours' },
        { id: 'game-session', name: 'Game Night', description: 'Board games and video games', duration: '2-4 hours' }
      ],
      wellness: [
        { id: 'gym-session', name: 'Group Workout', description: 'Fitness with accountability', duration: '1-2 hours' },
        { id: 'campus-walk', name: 'Campus Walk', description: 'Explore and get fresh air', duration: '30-60 minutes' },
        { id: 'mindfulness', name: 'Mindfulness Session', description: 'Meditation and relaxation', duration: '30-45 minutes' }
      ],
      creative: [
        { id: 'art-session', name: 'Art Creation Time', description: 'Draw, paint, create together', duration: '2-3 hours' },
        { id: 'music-practice', name: 'Music Practice', description: 'Jam sessions and practice', duration: '1-2 hours' },
        { id: 'writing-group', name: 'Writing Circle', description: 'Creative writing and feedback', duration: '1-2 hours' }
      ]
    };

    const frequencyOptions = [
      { id: 'daily', label: 'Daily', description: 'Every day at the same time' },
      { id: 'weekdays', label: 'Weekdays', description: 'Monday through Friday' },
      { id: 'weekly', label: 'Weekly', description: 'Same day each week' },
      { id: 'biweekly', label: 'Bi-weekly', description: 'Every other week' }
    ];

    const templates = ritualTemplates[selectedCategory as keyof typeof ritualTemplates] || [];

    return (
      <div className="w-full max-w-4xl mx-auto p-8 bg-gradient-to-br from-green-50 to-teal-50">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Create Campus Ritual</h2>
          <p className="text-lg text-gray-600">Start a regular activity that brings students together</p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Category Selection */}
          <div className="lg:col-span-1">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Ritual Category</CardTitle>
                <CardDescription>What type of activity?</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {ritualCategories.map((category) => {
                  const IconComponent = category.icon;
                  return (
                    <button
                      key={category.id}
                      onClick={() => setSelectedCategory(category.id)}
                      className={`w-full flex items-center gap-3 p-3 rounded-lg text-left transition-colors ${
                        selectedCategory === category.id
                          ? 'bg-green-600 text-white'
                          : 'hover:bg-gray-100'
                      }`}
                    >
                      <div className={`p-2 rounded-lg ${
                        selectedCategory === category.id
                          ? 'bg-white/20'
                          : category.color === 'blue' ? 'bg-blue-100 text-blue-600' :
                            category.color === 'green' ? 'bg-green-100 text-green-600' :
                            category.color === 'purple' ? 'bg-purple-100 text-purple-600' :
                            'bg-orange-100 text-orange-600'
                      }`}>
                        <IconComponent className="h-4 w-4" />
                      </div>
                      <div>
                        <p className="font-medium">{category.name}</p>
                        <p className={`text-sm ${
                          selectedCategory === category.id ? 'text-white/80' : 'text-gray-500'
                        }`}>
                          {category.count} active
                        </p>
                      </div>
                    </button>
                  );
                })}
              </CardContent>
            </Card>
          </div>

          {/* Ritual Templates & Configuration */}
          <div className="lg:col-span-2 space-y-6">
            {/* Template Selection */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  {selectedCategory === 'study' && <BookOpen className="h-5 w-5 text-blue-600" />}
                  {selectedCategory === 'social' && <Coffee className="h-5 w-5 text-green-600" />}
                  {selectedCategory === 'wellness' && <Dumbbell className="h-5 w-5 text-purple-600" />}
                  {selectedCategory === 'creative' && <Music className="h-5 w-5 text-orange-600" />}
                  {ritualCategories.find(c => c.id === selectedCategory)?.name} Templates
                </CardTitle>
                <CardDescription>Choose a starting point for your ritual</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  {templates.map((template) => (
                    <div
                      key={template.id}
                      onClick={() => setRitualType(template.id)}
                      className={`p-4 border-2 rounded-lg cursor-pointer transition-all ${
                        ritualType === template.id
                          ? 'border-green-500 bg-green-50'
                          : 'border-gray-200 hover:border-gray-300'
                      }`}
                    >
                      <div className="flex items-start justify-between">
                        <div>
                          <h3 className="font-semibold text-gray-900">{template.name}</h3>
                          <p className="text-gray-600 text-sm mt-1">{template.description}</p>
                          <div className="flex items-center gap-2 mt-2 text-xs text-gray-500">
                            <Clock className="h-3 w-3" />
                            <span>{template.duration}</span>
                          </div>
                        </div>
                        {ritualType === template.id && (
                          <CheckCircle className="h-5 w-5 text-green-600" />
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Frequency Selection */}
            {ritualType && (
              <Card>
                <CardHeader>
                  <CardTitle>Frequency & Schedule</CardTitle>
                  <CardDescription>How often will this ritual happen?</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    {frequencyOptions.map((option) => (
                      <div
                        key={option.id}
                        onClick={() => setFrequency(option.id)}
                        className={`p-4 border-2 rounded-lg cursor-pointer transition-all ${
                          frequency === option.id
                            ? 'border-green-500 bg-green-50'
                            : 'border-gray-200 hover:border-gray-300'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <div>
                            <p className="font-medium text-gray-900">{option.label}</p>
                            <p className="text-sm text-gray-600">{option.description}</p>
                          </div>
                          {frequency === option.id && (
                            <CheckCircle className="h-5 w-5 text-green-600" />
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Ritual Configuration */}
            {frequency && (
              <Card>
                <CardHeader>
                  <CardTitle>Ritual Details</CardTitle>
                  <CardDescription>Customize your ritual settings</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-medium text-gray-700 mb-2 block">
                        Ritual Name
                      </label>
                      <input
                        type="text"
                        placeholder="e.g., Morning Study Squad"
                        className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-700 mb-2 block">
                        Time
                      </label>
                      <input
                        type="time"
                        className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                      />
                    </div>
                  </div>
                  
                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Location
                    </label>
                    <input
                      type="text"
                      placeholder="e.g., Lockwood Library, 4th floor"
                      className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    />
                  </div>
                  
                  <div>
                    <label className="text-sm font-medium text-gray-700 mb-2 block">
                      Description
                    </label>
                    <textarea
                      placeholder="What will participants do? What should they bring? What's the vibe?"
                      rows={3}
                      className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-medium text-gray-700 mb-2 block">
                        Group Size
                      </label>
                      <select className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent">
                        <option>2-5 people (small group)</option>
                        <option>6-12 people (medium group)</option>
                        <option>13-25 people (large group)</option>
                        <option>Open to all (no limit)</option>
                      </select>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-gray-700 mb-2 block">
                        Experience Level
                      </label>
                      <select className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent">
                        <option>All levels welcome</option>
                        <option>Beginner friendly</option>
                        <option>Intermediate level</option>
                        <option>Advanced participants</option>
                      </select>
                    </div>
                  </div>

                  <div className="pt-4">
                    <Button className="w-full bg-green-600 hover:bg-green-700">
                      <Target className="h-4 w-4 mr-2" />
                      Create Ritual & Start Community
                    </Button>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        </div>

        <div className="mt-8 bg-emerald-50 rounded-xl p-6 border border-emerald-100">
          <h4 className="font-semibold text-emerald-900 mb-2">Campus Ritual Success Factors</h4>
          <ul className="text-sm text-emerald-800 space-y-1">
            <li>• Consistent timing builds habits and community expectation</li>
            <li>• Clear purpose attracts committed participants</li>
            <li>• Welcoming atmosphere encourages new members to join</li>
            <li>• Regular check-ins help rituals evolve with community needs</li>
          </ul>
        </div>
      </div>
    );
  }
};

// Ritual Participation Dashboard Story
export const RitualParticipationDashboard: Story = {
  render: () => {
    const [activeTab, setActiveTab] = React.useState('my-rituals');

    const myRituals = [
      {
        id: 'morning-gym',
        name: 'Morning Gym Squad',
        category: 'wellness',
        frequency: 'Daily',
        time: '7:00 AM',
        location: 'Alumni Arena',
        streak: 12,
        nextSession: 'Tomorrow, 7:00 AM',
        participants: 8,
        role: 'participant'
      },
      {
        id: 'study-session',
        name: 'CSE 474 Study Group',
        category: 'study',
        frequency: 'Bi-weekly',
        time: '2:00 PM',
        location: 'Lockwood Library',
        streak: 4,
        nextSession: 'Thursday, 2:00 PM',
        participants: 6,
        role: 'organizer'
      },
      {
        id: 'floor-potluck',
        name: 'Floor 3 Potluck',
        category: 'social',
        frequency: 'Weekly',
        time: '6:00 PM',
        location: 'Floor 3 Common Room',
        streak: 6,
        nextSession: 'Friday, 6:00 PM',
        participants: 18,
        role: 'participant'
      }
    ];

    const discoveredRituals = [
      {
        id: 'writing-circle',
        name: 'Creative Writing Circle',
        category: 'creative',
        frequency: 'Weekly',
        time: '7:00 PM',
        location: 'Campus Coffee Shop',
        participants: 8,
        organizer: 'Emma Thompson',
        description: 'Share creative writing and get constructive feedback in a supportive environment.'
      },
      {
        id: 'campus-photography',
        name: 'Campus Photography Walk',
        category: 'creative',
        frequency: 'Weekly',
        time: '5:00 PM',
        location: 'Varies by weather',
        participants: 12,
        organizer: 'Mike Davis',
        description: 'Explore campus and capture beautiful moments. All skill levels welcome!'
      }
    ];

    return (
      <div className="w-full max-w-6xl mx-auto p-8 bg-gradient-to-br from-purple-50 to-pink-50">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Ritual Participation Dashboard</h2>
          <p className="text-lg text-gray-600">Track your regular campus activities and discover new ones</p>
        </div>

        {/* Tab Navigation */}
        <div className="flex justify-center mb-8">
          <div className="flex bg-white rounded-lg p-1 shadow-sm">
            {[
              { id: 'my-rituals', label: 'My Rituals', count: myRituals.length },
              { id: 'discover', label: 'Discover', count: discoveredRituals.length }
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`px-6 py-3 rounded-lg font-medium transition-colors ${
                  activeTab === tab.id
                    ? 'bg-purple-600 text-white'
                    : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                {tab.label} ({tab.count})
              </button>
            ))}
          </div>
        </div>

        {/* My Rituals Tab */}
        {activeTab === 'my-rituals' && (
          <div className="space-y-6">
            {/* Stats Overview */}
            <div className="grid md:grid-cols-3 gap-6">
              <Card>
                <CardContent className="p-6 text-center">
                  <div className="text-3xl font-bold text-purple-600">3</div>
                  <div className="text-gray-600">Active Rituals</div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 text-center">
                  <div className="text-3xl font-bold text-green-600">22</div>
                  <div className="text-gray-600">Total Streak Days</div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 text-center">
                  <div className="text-3xl font-bold text-blue-600">32</div>
                  <div className="text-gray-600">Community Members</div>
                </CardContent>
              </Card>
            </div>

            {/* Ritual Cards */}
            <div className="grid lg:grid-cols-2 gap-6">
              {myRituals.map((ritual) => (
                <Card key={ritual.id} className="overflow-hidden">
                  <CardHeader className="pb-3">
                    <div className="flex items-start justify-between">
                      <div>
                        <CardTitle className="flex items-center gap-2">
                          {ritual.category === 'wellness' && <Dumbbell className="h-5 w-5 text-purple-600" />}
                          {ritual.category === 'study' && <BookOpen className="h-5 w-5 text-blue-600" />}
                          {ritual.category === 'social' && <Coffee className="h-5 w-5 text-green-600" />}
                          {ritual.name}
                        </CardTitle>
                        <div className="flex items-center gap-2 mt-1">
                          <Badge variant={ritual.role === 'organizer' ? 'default' : 'secondary'} className="text-xs">
                            {ritual.role}
                          </Badge>
                          <Badge variant="outline" className="text-xs">
                            {ritual.frequency}
                          </Badge>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="flex items-center gap-1 text-sm text-orange-600">
                          <Trophy className="h-4 w-4" />
                          <span>{ritual.streak} day streak</span>
                        </div>
                      </div>
                    </div>
                  </CardHeader>

                  <CardContent className="space-y-4">
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div>
                        <div className="flex items-center gap-1 text-gray-600">
                          <Clock className="h-3 w-3" />
                          <span>{ritual.time}</span>
                        </div>
                      </div>
                      <div>
                        <div className="flex items-center gap-1 text-gray-600">
                          <MapPin className="h-3 w-3" />
                          <span>{ritual.location}</span>
                        </div>
                      </div>
                      <div>
                        <div className="flex items-center gap-1 text-gray-600">
                          <Users className="h-3 w-3" />
                          <span>{ritual.participants} participants</span>
                        </div>
                      </div>
                      <div>
                        <div className="flex items-center gap-1 text-gray-600">
                          <Calendar className="h-3 w-3" />
                          <span>{ritual.nextSession}</span>
                        </div>
                      </div>
                    </div>

                    <div className="flex gap-2">
                      <Button size="sm" className="flex-1">
                        <CheckCircle className="h-4 w-4 mr-2" />
                        Confirm Next Session
                      </Button>
                      {ritual.role === 'organizer' && (
                        <Button size="sm" variant="outline">
                          <Settings className="h-4 w-4" />
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        )}

        {/* Discover Tab */}
        {activeTab === 'discover' && (
          <div className="space-y-6">
            <div className="text-center">
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Discover New Rituals</h3>
              <p className="text-gray-600">Join activities happening around campus</p>
            </div>

            <div className="grid lg:grid-cols-2 gap-6">
              {discoveredRituals.map((ritual) => (
                <Card key={ritual.id} className="overflow-hidden">
                  <CardHeader className="pb-3">
                    <div className="flex items-start justify-between">
                      <div>
                        <CardTitle className="flex items-center gap-2">
                          {ritual.category === 'creative' && <Music className="h-5 w-5 text-orange-600" />}
                          {ritual.name}
                        </CardTitle>
                        <p className="text-sm text-gray-600 mt-1">by {ritual.organizer}</p>
                      </div>
                      <Badge variant="outline" className="text-xs">
                        {ritual.frequency}
                      </Badge>
                    </div>
                  </CardHeader>

                  <CardContent className="space-y-4">
                    <p className="text-gray-700 text-sm">{ritual.description}</p>
                    
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div>
                        <div className="flex items-center gap-1 text-gray-600">
                          <Clock className="h-3 w-3" />
                          <span>{ritual.time}</span>
                        </div>
                      </div>
                      <div>
                        <div className="flex items-center gap-1 text-gray-600">
                          <MapPin className="h-3 w-3" />
                          <span>{ritual.location}</span>
                        </div>
                      </div>
                      <div className="col-span-2">
                        <div className="flex items-center gap-1 text-gray-600">
                          <Users className="h-3 w-3" />
                          <span>{ritual.participants} current participants</span>
                        </div>
                      </div>
                    </div>

                    <div className="flex gap-2">
                      <Button size="sm" className="flex-1 bg-purple-600 hover:bg-purple-700">
                        <Plus className="h-4 w-4 mr-2" />
                        Join Ritual
                      </Button>
                      <Button size="sm" variant="outline">
                        <MessageCircle className="h-4 w-4 mr-2" />
                        Ask Questions
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        )}

        <div className="mt-8 bg-violet-50 rounded-xl p-6 border border-violet-100">
          <h4 className="font-semibold text-violet-900 mb-2">Building Campus Community Through Rituals</h4>
          <ul className="text-sm text-violet-800 space-y-1">
            <li>• Regular activities create lasting friendships and campus connections</li>
            <li>• Streaks and consistency build positive habits and accountability</li>
            <li>• Diverse ritual categories ensure everyone finds their community</li>
            <li>• Organizer tools help students become campus community leaders</li>
          </ul>
        </div>
      </div>
    );
  }
};