import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { dbAdmin } from '@/lib/firebase-admin';

/**
 * Initialize cohort space collection structure in Firebase
 * This creates the necessary Firestore collection structure for cohort spaces
 */
export async function POST(request: NextRequest) {
  try {
    console.log('🎓 Initializing cohort space collection structure...');
    
    // Create the cohort collection document with metadata
    const cohortCollectionRef = dbAdmin.collection('spaces').doc('cohort');
    
    // Check if it already exists
    const cohortDoc = await cohortCollectionRef.get();
    
    if (cohortDoc.exists) {
      console.log('📋 Cohort collection already exists');
      
      // Get current count of cohort spaces
      const cohortSpacesSnapshot = await cohortCollectionRef.collection('spaces').get();
      
      return NextResponse.json({
        success: true,
        message: 'Cohort collection already exists',
        alreadyExists: true,
        currentCohortSpaces: cohortSpacesSnapshot.size,
        structure: 'spaces/cohort/spaces/{spaceId}'
      });
    }
    
    // Create the cohort collection document with metadata
    await cohortCollectionRef.set({
      type: 'cohort',
      description: 'Academic cohort spaces for majors and graduation years',
      createdAt: new Date(),
      structure: 'Nested collection: spaces/cohort/spaces/{spaceId}',
      cohortTypes: [
        'major', // e.g., "Computer Science"
        'graduation_year', // e.g., "Class of '25"
        'major_year' // e.g., "CS '25"
      ],
      autoCreated: true,
      version: '1.0'
    });
    
    console.log('✅ Created cohort collection structure');
    
    // Create a sample cohort space to initialize the subcollection
    const sampleSpaceRef = cohortCollectionRef.collection('spaces').doc('sample-cohort');
    await sampleSpaceRef.set({
      name: 'Sample Cohort',
      description: 'This is a sample cohort space to initialize the collection structure. It can be safely deleted.',
      type: 'cohort',
      status: 'dormant',
      memberCount: 0,
      tags: [
        {
          type: 'cohort',
          sub_type: 'sample'
        }
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
      name_lowercase: 'sample cohort',
      schoolId: 'university',
      pinnedPostId: null,
      bannerUrl: null,
      isAutoGenerated: true,
      isSample: true,
      cohortData: {
        major: null,
        graduationYear: null,
        cohortType: 'sample'
      }
    });
    
    console.log('✅ Created sample cohort space to initialize subcollection');
    
    return NextResponse.json({
      success: true,
      message: 'Cohort collection structure created successfully',
      created: true,
      structure: {
        collection: 'spaces/cohort',
        subcollection: 'spaces/cohort/spaces',
        sampleSpaceId: 'sample-cohort'
      },
      nextSteps: [
        'Use /api/spaces/cohort/auto-create to create user-specific cohort spaces',
        'Use /api/spaces/seed to populate with additional cohort spaces',
        'Use /api/spaces/diagnostic to verify the structure'
      ]
    });
    
  } catch (error: any) {
    console.error('Cohort collection initialization error:', error);
    
    return NextResponse.json(
      { 
        error: 'Failed to initialize cohort collection',
        details: error.message,
        structure: 'spaces/cohort/spaces/{spaceId}'
      },
      { status: 500 }
    );
  }
}

/**
 * Get information about the cohort collection structure
 */
export async function GET() {
  try {
    const cohortCollectionRef = dbAdmin.collection('spaces').doc('cohort');
    const cohortDoc = await cohortCollectionRef.get();
    
    if (!cohortDoc.exists) {
      return NextResponse.json({
        exists: false,
        message: 'Cohort collection not initialized',
        suggestion: 'POST to this endpoint to initialize the collection structure'
      });
    }
    
    // Get count of cohort spaces
    const cohortSpacesSnapshot = await cohortCollectionRef.collection('spaces').get();
    const sampleSpaces = cohortSpacesSnapshot.docs.slice(0, 3).map(doc => ({
      id: doc.id,
      name: doc.data().name,
      cohortType: doc.data().cohortData?.cohortType || 'unknown'
    }));
    
    return NextResponse.json({
      exists: true,
      metadata: cohortDoc.data(),
      cohortSpacesCount: cohortSpacesSnapshot.size,
      sampleSpaces,
      structure: 'spaces/cohort/spaces/{spaceId}'
    });
    
  } catch (error: any) {
    return NextResponse.json(
      { error: 'Failed to check cohort collection', details: error.message },
      { status: 500 }
    );
  }
}