declare module "@hive/ui" {
  // Navigation types
  export type HiveNavId = "feed" | "spaces" | "recents" | "profile" | "hivelab" | "settings";
  export function getHiveNav(isLeader: boolean): Array<{ id: HiveNavId; label: string; href: string; icon: any; requiresLeader?: boolean }>;

  export const Banner: any;
  export const Button: any;
  export const Card: any;
  export const CardContent: any;
  export const CardDescription: any;
  export const CardHeader: any;
  export const CardTitle: any;
  export const CardFooter: any;
  export const Heading: any;
  export const Text: any;
  export const Input: any;
  export const RadioGroup: any;
  export const RadioGroupItem: any;
  export const useToast: any;
  export const Badge: any;
  export const Checkbox: any;
  export const CheckboxGroup: any;
  export const FormField: any;
  export const FormFieldControl: any;
  export const StepperHeader: any;
  export const Separator: any;
  export const Breadcrumb: any;
  export const BreadcrumbList: any;
  export const BreadcrumbItem: any;
  export const BreadcrumbLink: any;
  export const BreadcrumbPage: any;
  export const BreadcrumbSeparator: any;
  export const TagInput: any;
  export const Popover: any;
  export const PopoverTrigger: any;
  export const PopoverContent: any;
  export const Command: any;
  export const CommandInput: any;
  export const CommandList: any;
  export const CommandItem: any;
  export const CommandEmpty: any;
  export const CommandGroup: any;
  export const Spinner: any;
  export const DropdownMenu: any;
  export const DropdownMenuTrigger: any;
  export const DropdownMenuContent: any;
  export const DropdownMenuItem: any;
  export const DropdownMenuSeparator: any;
  export const Avatar: any;
  export const Switch: any;
  export const InlineNotice: any;
  export const AuthMagicLinkCard: any;
  export const ThemeProvider: any;
  export const Toaster: any;
  export const SidebarProvider: any;
  export const SidebarInset: any;
  export const SidebarTrigger: any;
  export const AppSidebar: any;
  export const AppSidebarHive: any;
  export const AppSidebarAdmin: any;
  export const AppSidebarCompact: any;
  export const cn: any;
  const hiveUi: any;
  export default hiveUi;
}
