/**
 * Auto Space Creation API
 * 
 * Creates spaces automatically based on user's academic information
 * during onboarding or profile updates.
 */

import { NextRequest, NextResponse } from 'next/server';
import { logger } from '@hive/core/utils/logger';

import { generateAutoSpaces, type AutoSpaceConfig } from '@/lib/auto-space-creation';

export async function POST(request: NextRequest) {
  try {
    // Get auth token from request
    const authHeader = request.headers.get('authorization');
    if (!authHeader) {
      return NextResponse.json(
        { error: 'Authorization required' },
        { status: 401 }
      );
    }

    const token = authHeader.replace('Bearer ', '');
    
    // Parse request body
    const body = await request.json();
    const { schoolId, graduationYear, major, year, userType } = body as AutoSpaceConfig;

    // Validate required fields
    if (!schoolId || !major || !userType) {
      return NextResponse.json(
        { error: 'Missing required fields: schoolId, major, userType' },
        { status: 400 }
      );
    }

    // Generate space templates
    const spaceTemplates = generateAutoSpaces({
      schoolId,
      graduationYear,
      major,
      year,
      userType
    });

    const results = {
      created: [] as string[],
      joined: [] as string[],
      errors: [] as string[],
      recommended: [] as any[]
    };

    // Process each space template
    for (const template of spaceTemplates) {
      try {
        // 1. Check if space already exists
        const existsResponse = await fetch(`${request.nextUrl.origin}/api/spaces/${template.id}`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });

        let spaceExists = existsResponse.ok;

        // 2. Create space if it doesn't exist
        if (!spaceExists) {
          const createResponse = await fetch(`${request.nextUrl.origin}/api/spaces`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify({
              id: template.id,
              name: template.name,
              description: template.description,
              type: template.type,
              category: template.category,
              membershipType: template.membershipType,
              isAutoGenerated: true,
              tags: ['auto-created', template.category.toLowerCase(), template.type],
              settings: {
                isPublic: template.membershipType === 'open',
                allowInvites: true,
                allowDiscovery: true,
                autoGenerated: true
              },
              metadata: {
                createdBy: 'auto-space-system',
                createdAt: new Date().toISOString(),
                academicInfo: {
                  schoolId,
                  graduationYear,
                  major,
                  year,
                  userType
                }
              }
            })
          });

          if (createResponse.ok) {
            results.created.push(template.name);
            spaceExists = true;
          } else {
            const createError = await createResponse.text();
            console.warn(`Failed to create space ${template.name}:`, createError);
            results.errors.push(`Failed to create ${template.name}`);
            continue;
          }
        }

        // 3. Auto-join user to space if enabled
        if (spaceExists && template.autoJoin) {
          const joinResponse = await fetch(`${request.nextUrl.origin}/api/spaces/${template.id}/membership`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify({
              action: 'join',
              isAutoJoin: true,
              source: 'onboarding'
            })
          });

          if (joinResponse.ok) {
            results.joined.push(template.name);
          } else {
            const joinError = await joinResponse.text();
            console.warn(`Failed to join space ${template.name}:`, joinError);
            results.errors.push(`Failed to join ${template.name}`);
          }
        }

        // 4. Add to recommendations if not auto-joined
        if (spaceExists && template.isRecommended && !template.autoJoin) {
          results.recommended.push({
            id: template.id,
            name: template.name,
            description: template.description,
            type: template.type,
            category: template.category
          });
        }

      } catch (error) {
        logger.error('Error processing space ${template.name}:', error);
        results.errors.push(`Error processing ${template.name}: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
    }

    // Log results for monitoring
    return NextResponse.json({
      success: true,
      results,
      summary: {
        totalProcessed: spaceTemplates.length,
        created: results.created.length,
        joined: results.joined.length,
        recommended: results.recommended.length,
        errors: results.errors.length
      }
    });

  } catch (error) {
    logger.error('Auto-space creation API error:', error);
    return NextResponse.json(
      { 
        error: 'Internal server error',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// GET endpoint to preview what spaces would be created
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const schoolId = searchParams.get('schoolId');
    const graduationYear = parseInt(searchParams.get('graduationYear') || '0');
    const major = searchParams.get('major');
    const year = searchParams.get('year') as any;
    const userType = searchParams.get('userType') as any;

    if (!schoolId || !major || !userType) {
      return NextResponse.json(
        { error: 'Missing required query parameters: schoolId, major, userType' },
        { status: 400 }
      );
    }

    const spaceTemplates = generateAutoSpaces({
      schoolId,
      graduationYear,
      major,
      year,
      userType
    });

    return NextResponse.json({
      preview: true,
      spaces: spaceTemplates.map(template => ({
        id: template.id,
        name: template.name,
        description: template.description,
        type: template.type,
        category: template.category,
        autoJoin: template.autoJoin,
        isRecommended: template.isRecommended,
        membershipType: template.membershipType
      })),
      summary: {
        total: spaceTemplates.length,
        autoJoin: spaceTemplates.filter(s => s.autoJoin).length,
        recommended: spaceTemplates.filter(s => s.isRecommended && !s.autoJoin).length
      }
    });

  } catch (error) {
    logger.error('Auto-space preview API error:', error);
    return NextResponse.json(
      { 
        error: 'Internal server error',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}