/**
 * Centralized logging system for HIVE application
 * Replaces console.log statements with proper structured logging
 */

import { config } from './config';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

interface LogContext {
  userId?: string;
  spaceId?: string;
  toolId?: string;
  component?: string;
  action?: string;
  endpoint?: string;
  error?: Error | string | any;
  data?: any;
  metadata?: Record<string, any>;
  // Additional properties found in codebase
  stack?: string;
  requestId?: string;
  requestData?: any;
  adminUserId?: string;
  analyticsData?: any;
  builderRequestId?: string;
  cohortData?: any;
  memberUserId?: string;
  moderatorId?: string;
  membershipData?: any;
  auditData?: any;
  permissionData?: any;
  spacesData?: any;
  bulkData?: any;
  usersData?: any;
  userData?: any;
  oldData?: any;
  newData?: any;
  authToken?: string;
  sessionData?: any;
  calendarData?: any;
  eventData?: any;
  conflictData?: any;
  feedData?: any;
  debugData?: any;
  authData?: any;
  fileData?: any;
  notificationData?: any;
  privacyData?: any;
  profileData?: any;
  activityData?: any;
  completionData?: any;
  avatarData?: any;
  spaceData?: any;
  memberData?: any;
  postData?: any;
  widgetData?: any;
  activationData?: any;
  joinData?: any;
  leaveData?: any;
  migrationData?: any;
  seedData?: any;
  socialProofData?: any;
  testData?: any;
  updateData?: any;
  deploymentData?: any;
  reviewData?: any;
  stateData?: any;
  executeData?: any;
  integrationData?: any;
  installData?: any;
  personalData?: any;
  publishData?: any;
  recommendationData?: any;
  usageData?: any;
  waitlistData?: any;
  // Additional properties found in recent codebase usage
  attempt?: number;
  attempts?: number;
  autoGeneratedSpaces?: any;
  cohortSpacesLength?: number;
  componentStack?: string;
  connectionCount?: number;
  connectionId?: string;
  count?: number;
  created?: boolean;
  currentCount?: number;
  durationMinutes?: number;
  email?: string;
  emailDomain?: string;
  eventCount?: number;
  exists?: boolean;
  feedType?: string;
  finalTotal?: number;
  fromSpaceId?: string;
  graduationYearsLength?: number;
  handle?: string;
  id?: string;
  isDevelopmentUser?: boolean;
  major?: string;
  matchingSpace?: any;
  memberships?: any;
  membershipsSnapshot?: any;
  method?: string;
  notificationId?: string;
  oldEventsSnapshot?: any;
  oldSummariesSnapshot?: any;
  operationCount?: number;
  operationId?: string;
  operationsCompleted?: number;
  projectId?: string;
  queryParams?: any;
  requestRefId?: string;
  result?: any;
  ritualCount?: number;
  ritualDataName?: string;
  ritualId?: string;
  sourceId?: string;
  sourceType?: string;
  spaceConfig?: any;
  spaceConfigId?: string;
  spaceCount?: number;
  spaces?: any;
  spacesSnapshot?: any;
  spacesWithoutUB?: any;
  spaceType?: string;
  status?: string;
  targetId?: string;
  targetTotal?: number;
  targetUserId?: string;
  timeRange?: string;
  toolDataOwnerId?: string;
  toolRefId?: string;
  type?: string;
  UB_MAJORSLength?: number;
  userSpaceIds?: any;
  userUid?: string;
  // Additional recently found properties
  currentRitual?: any;
  isLocalEnvironment?: boolean;
  schoolId?: string;
  size?: number;
  spaceName?: string;
  targetCount?: number;
  toSpaceId?: string;
  totalConnections?: number;
  totalToCreate?: number;
  // Additional error boundary and system properties
  errorBoundary?: string;
  spaceContext?: string;
}

interface LogEntry {
  level: LogLevel;
  message: string;
  timestamp: string;
  context?: LogContext;
  error?: Error;
}

class Logger {
  private isDevelopment = config.app.environment === 'development';
  private enableConsole = config.logging.enableConsole;

  private formatMessage(entry: LogEntry): string {
    const { timestamp, level, message, context } = entry;
    const contextStr = context ? ` [${JSON.stringify(context)}]` : '';
    return `[${timestamp}] ${level.toUpperCase()}: ${message}${contextStr}`;
  }

  private shouldLog(level: LogLevel): boolean {
    const levels: Record<LogLevel, number> = {
      debug: 0,
      info: 1,
      warn: 2,
      error: 3,
    };
    
    const configLevel = config.logging.level as LogLevel;
    return levels[level] >= levels[configLevel];
  }

  private createLogEntry(level: LogLevel, message: string, context?: LogContext, error?: Error): LogEntry {
    return {
      level,
      message,
      timestamp: new Date().toISOString(),
      context,
      error,
    };
  }

  private log(entry: LogEntry): void {
    if (!this.shouldLog(entry.level)) return;

    // Console logging for development
    if (this.enableConsole) {
      const formattedMessage = this.formatMessage(entry);
      
      switch (entry.level) {
        case 'debug':
          console.debug(formattedMessage, entry.error);
          break;
        case 'info':
          console.info(formattedMessage);
          break;
        case 'warn':
          console.warn(formattedMessage, entry.error);
          break;
        case 'error':
          console.error(formattedMessage, entry.error);
          break;
      }
    }

    // TODO: Send to external logging service (e.g., Datadog, LogRocket)
    // if (config.logging.enableExternal) {
    //   this.sendToExternalService(entry);
    // }

    // TODO: Send errors to Sentry
    // if (entry.level === 'error' && config.logging.enableSentry && entry.error) {
    //   Sentry.captureException(entry.error, { contexts: { custom: entry.context } });
    // }
  }

  debug(message: string, context?: LogContext): void {
    this.log(this.createLogEntry('debug', message, context));
  }

  info(message: string, context?: LogContext): void {
    this.log(this.createLogEntry('info', message, context));
  }

  warn(message: string, context?: LogContext, error?: Error): void {
    this.log(this.createLogEntry('warn', message, context, error));
  }

  error(message: string, context?: LogContext, error?: Error): void {
    this.log(this.createLogEntry('error', message, context, error));
  }

  // Specialized logging methods for common patterns
  apiCall(endpoint: string, method: string, context?: LogContext): void {
    this.debug(`API Call: ${method} ${endpoint}`, {
      ...context,
      action: 'api_call',
      metadata: { endpoint, method },
    });
  }

  userAction(action: string, context?: LogContext): void {
    this.info(`User Action: ${action}`, {
      ...context,
      action: 'user_action',
    });
  }

  spaceEvent(event: string, spaceId: string, context?: LogContext): void {
    this.info(`Space Event: ${event}`, {
      ...context,
      spaceId,
      action: 'space_event',
    });
  }

  authEvent(event: string, context?: LogContext): void {
    this.info(`Auth Event: ${event}`, {
      ...context,
      action: 'auth_event',
    });
  }

  performanceStart(operation: string): () => void {
    const startTime = performance.now();
    
    return () => {
      const duration = performance.now() - startTime;
      this.debug(`Performance: ${operation} completed in ${duration.toFixed(2)}ms`, {
        action: 'performance',
        metadata: { operation, duration },
      });
    };
  }
}

// Export singleton instance
export const logger = new Logger();

// Export convenience functions
export const { debug, info, warn, error, apiCall, userAction, spaceEvent, authEvent } = logger;