import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { dbAdmin } from '@/lib/firebase-admin';
import { UB_MAJORS, createMajorAbbreviation } from '@hive/core';
import { logger } from "@/lib/structured-logger";
import { ApiResponseHelper as _ApiResponseHelper, HttpStatus, ErrorCodes } from "@/lib/api-response-types";

/**
 * Seed UB-specific cohort spaces based on actual UB majors and graduation years
 */
export async function POST(request: NextRequest) {
  try {
    const { dryRun = false, years = ['24', '25', '26', '27', '28'] } = await request.json().catch(() => ({}));
    
    logger.info('🎓 Starting UB cohort space seeding...', { endpoint: '/api/spaces/cohort/seed-ub' });
    
    const currentYear = new Date().getFullYear();
    const graduationYears = years.map((y: string) => {
      // Convert 2-digit to 4-digit year
      const fullYear = y.length === 2 ? parseInt(`20${y}`) : parseInt(y);
      return fullYear;
    });
    
    // Create cohort spaces for UB
    const cohortSpaces = [];
    
    // 1. Create major-specific spaces (all years)
    for (const major of UB_MAJORS) {
      const majorId = major.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
      const majorAbbrev = createMajorAbbreviation(major.name);
      
      cohortSpaces.push({
        id: `ub-major-${majorId}`,
        name: `UB ${major.name}`,
        description: `Connect with University at Buffalo ${major.name} students across all graduation years for academic support, study groups, and career networking.`,
        type: 'cohort',
        status: 'activated',
        memberCount: Math.floor(Math.random() * 300) + 50, // 50-350 members
        schoolId: 'university-at-buffalo',
        university: 'University at Buffalo',
        universityShort: 'UB',
        tags: [
          {
            type: 'cohort',
            sub_type: 'major'
          },
          {
            type: 'cohort', 
            sub_type: major.school.toLowerCase().replace(/[^a-z0-9]/g, '-')
          }
        ],
        cohortData: {
          major: major.name,
          school: major.school,
          graduationYear: null,
          cohortType: 'major',
          university: 'University at Buffalo'
        },
        isAutoGenerated: true,
        seedingVersion: '2.0-ub',
        createdAt: new Date(),
        updatedAt: new Date(),
        name_lowercase: `ub ${major.name}`.toLowerCase()
      });
    }
    
    // 2. Create graduation year spaces (all majors)
    for (const year of graduationYears) {
      const shortYear = year.toString().slice(-2);
      
      cohortSpaces.push({
        id: `ub-class-${year}`,
        name: `UB Class of '${shortYear}`,
        description: `University at Buffalo students graduating in ${year}. Connect with your class across all majors for networking, events, and lifelong friendships.`,
        type: 'cohort',
        status: 'activated',
        memberCount: Math.floor(Math.random() * 2000) + 500, // 500-2500 members per class
        schoolId: 'university-at-buffalo',
        university: 'University at Buffalo',
        universityShort: 'UB',
        tags: [
          {
            type: 'cohort',
            sub_type: 'graduation_year'
          }
        ],
        cohortData: {
          major: null,
          graduationYear: year,
          cohortType: 'graduation_year',
          university: 'University at Buffalo'
        },
        isAutoGenerated: true,
        seedingVersion: '2.0-ub',
        createdAt: new Date(),
        updatedAt: new Date(),
        name_lowercase: `ub class of '${shortYear}`.toLowerCase()
      });
    }
    
    // 3. Create popular major+year combinations
    const popularMajors = [
      'Computer Science',
      'Business Administration', 
      'Engineering',
      'Psychology',
      'Biology',
      'Nursing',
      'Communications',
      'Economics',
      'Pre-Med'
    ];
    
    for (const majorName of popularMajors) {
      const major = UB_MAJORS.find(m => m.name === majorName) || UB_MAJORS.find(m => m.name.includes(majorName.split(' ')[0]));
      if (!major) continue;
      
      for (const year of graduationYears) {
        const shortYear = year.toString().slice(-2);
        const majorAbbrev = createMajorAbbreviation(major.name);
        const majorId = major.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
        
        cohortSpaces.push({
          id: `ub-cohort-${majorId}-${year}`,
          name: `UB ${majorAbbrev} '${shortYear}`,
          description: `University at Buffalo ${major.name} students graduating in ${year}. Your core academic cohort for study groups, project collaboration, and career networking.`,
          type: 'cohort',
          status: 'activated',
          memberCount: Math.floor(Math.random() * 80) + 15, // 15-95 members
          schoolId: 'university-at-buffalo',
          university: 'University at Buffalo',
          universityShort: 'UB',
          tags: [
            {
              type: 'cohort',
              sub_type: 'major_year'
            },
            {
              type: 'cohort',
              sub_type: major.school.toLowerCase().replace(/[^a-z0-9]/g, '-')
            }
          ],
          cohortData: {
            major: major.name,
            school: major.school,
            graduationYear: year,
            cohortType: 'major_year',
            university: 'University at Buffalo'
          },
          isAutoGenerated: true,
          seedingVersion: '2.0-ub',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_lowercase: `ub ${majorAbbrev} '${shortYear}`.toLowerCase()
        });
      }
    }
    
    logger.info('📊 Generated UB cohort spaces', { cohortSpacesLength: cohortSpaces.length, endpoint: '/api/spaces/cohort/seed-ub'  });
    logger.info('- major spaces', { UB_MAJORSLength: UB_MAJORS.length, endpoint: '/api/spaces/cohort/seed-ub'  });
    logger.info('- class year spaces', { graduationYearsLength: graduationYears.length, endpoint: '/api/spaces/cohort/seed-ub'  });
    logger.info('- major+year spaces', { count: popularMajors.length * graduationYears.length, endpoint: '/api/spaces/cohort/seed-ub' });
    
    if (dryRun) {
      return NextResponse.json({
        success: true,
        dryRun: true,
        summary: {
          totalSpaces: cohortSpaces.length,
          majorSpaces: UB_MAJORS.length,
          yearSpaces: graduationYears.length,
          majorYearSpaces: popularMajors.length * graduationYears.length,
          graduationYears: graduationYears
        },
        sampleSpaces: cohortSpaces.slice(0, 5).map(s => ({
          id: s.id,
          name: s.name,
          cohortType: s.cohortData.cohortType
        })),
        university: 'University at Buffalo'
      });
    }
    
    // Create spaces in Firebase batches
    logger.info('🔥 Creating UB cohort spaces in Firebase...', { endpoint: '/api/spaces/cohort/seed-ub' });
    
    const batchSize = 500; // Firestore batch limit
    const batches = [];
    
    for (let i = 0; i < cohortSpaces.length; i += batchSize) {
      const batch = dbAdmin.batch();
      const batchSpaces = cohortSpaces.slice(i, i + batchSize);
      
      for (const space of batchSpaces) {
        const spaceRef = dbAdmin
          .collection('spaces')
          .doc('cohort')
          .collection('spaces')
          .doc(space.id);
          
        batch.set(spaceRef, space);
      }
      
      batches.push(batch);
    }
    
    // Execute all batches
    let created = 0;
    for (const batch of batches) {
      await batch.commit();
      created += batchSize;
      logger.info('✅ Created batch of spaces', { count: created, total: cohortSpaces.length, endpoint: '/api/spaces/cohort/seed-ub' });
    }
    
    logger.info('🎉 Successfully created UB cohort spaces', { cohortSpacesLength: cohortSpaces.length, endpoint: '/api/spaces/cohort/seed-ub'  });
    
    return NextResponse.json({
      success: true,
      message: `Created ${cohortSpaces.length} UB cohort spaces`,
      university: 'University at Buffalo',
      summary: {
        totalSpaces: cohortSpaces.length,
        majorSpaces: UB_MAJORS.length,
        yearSpaces: graduationYears.length,
        majorYearSpaces: popularMajors.length * graduationYears.length,
        graduationYears: graduationYears
      },
      created: cohortSpaces.length
    });
    
  } catch (error: any) {
    logger.error('UB cohort seeding error', { error: error, endpoint: '/api/spaces/cohort/seed-ub' });
    
    return NextResponse.json(
      { 
        error: 'Failed to seed UB cohort spaces',
        details: error.message,
        university: 'University at Buffalo'
      },
      { status: HttpStatus.INTERNAL_SERVER_ERROR }
    );
  }
}

/**
 * Get information about UB cohort seeding
 */
export async function GET() {
  return NextResponse.json({
    info: 'UB Cohort Space Seeding API',
    university: 'University at Buffalo',
    description: 'Creates cohort spaces based on actual UB majors and graduation years',
    usage: {
      dryRun: 'POST with { dryRun: true } to preview spaces',
      create: 'POST with { dryRun: false } to create spaces',
      years: 'POST with { years: ["24", "25", "26"] } to specify graduation years'
    },
    totals: {
      majorSpaces: UB_MAJORS.length,
      defaultYearSpaces: 5, // '24, '25, '26, '27, '28
      popularMajorYearCombos: 9 * 5, // 9 popular majors x 5 years
      estimatedTotal: UB_MAJORS.length + 5 + (9 * 5)
    },
    ubMajorsIncluded: UB_MAJORS.length,
    schools: [...new Set(UB_MAJORS.map(m => m.school))].sort()
  });
}